SELECT A.PRODUCT_CODE, B.NUM * A.PRICE AS SALES
FROM PRODUCT A INNER JOIN (
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS NUM
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, A.PRODUCT_CODE